EsupPortail/Esup-Pod

pod/main/admin.py

Add template_name option to flatpage fieldsets tuple

---

pod/authentication/models.py
pod/authentication/populatedCASbackend.py
pod/settings.py
pod/video/admin.py
pod/video/models.py

Add Owner establishment attribute

---

pod/completion/forms.py
pod/completion/static/css/caption_maker.css
pod/completion/static/js/caption_maker.js
pod/completion/static/js/completion.js
pod/completion/templates/track/list_track.html
pod/completion/templates/video_caption_maker.html
pod/completion/templates/video_caption_maker_modal.html
pod/completion/templates/video_completion.html
pod/completion/views.py
pod/podfile/forms.py
pod/podfile/static/js/filewidget.js
pod/podfile/urls.py
pod/podfile/views.py

Caption maker page reworked
- add charge file from podfile
- change save system (and change UI for it)
- add support for audio only files (videoJS)

Caption maker page

---

pod/completion/views.py

@ptitloup Amélioration de la fonctionnalité de lien cliquable sur les textes de superposition.
Objectif: Enlever le lien HTML lorsqu'un utilisateur modifie son texte de superposition.
**settings_local variable**  => **LINK_SUPERPOSITION** = True
**Fonctionnalité** : Lorsqu'un utilisateur introduit une URL dans son texte, le programme détecte son URL et la transforme en lien HTML cliquable lors de la lecture de la vidéo.

Remove html link on editing overlay text

---

pod/custom/urls.py
pod/urls.py

@ptitloup 
Il me semble que ça a été mentionné lors de la dernière réunion et c'est également une option qui m’intéresse.

Add custom urls

---

pod/settings.py
pod/urls.py
pod/video/models.py
requirements.txt

Add filter to select field

---

pod/video/models.py

Revision of the logic of the code when saving a theme

---

pod/video/static/js/video_stats_view.js

Fix bug stats on change pagination

---

pod/locale/fr/LC_MESSAGES/django.po
pod/locale/nl/LC_MESSAGES/django.po
pod/main/context_processors.py
pod/video/models.py
pod/video/views.py

Reverts EsupPortail/Esup-Pod#227

Revert "Exclude not encoded video from last videos page + prevent issues with…"

---

pod/main/templates/base.html

Hello,
Toute petite PR qui permet de mettre un bootstrap customisé. Une fois installé, normalement, il ne devrait rien se passer. Il faut ensuite ajouter le fichier bootstrap.min.css joint dans le dossier main/static/custom et modifier le fichier settings_local.py en ajoutant 'BOOTSTRAP_CUSTOM': 'custom/bootstrap.min.css', dans la variable TEMPLATE_VISIBLE_SETTINGS.
[bootstrap.min.zip](https://github.com/EsupPortail/Esup-Pod/files/4411640/bootstrap.min.zip)

Add possibility for custom bootstrap

---

pod/enrichment/static/js/enrichment.js
pod/enrichment/templates/enrichment/edit_enrichment.html
pod/enrichment/templates/enrichment/form_enrichment.html
pod/enrichment/templates/enrichment/group_enrichment.html
pod/enrichment/templates/enrichment/list_enrichment.html
pod/interactive/templates/interactive/edit_interactive.html
pod/interactive/templates/interactive/group_interactive.html
pod/interactive/templates/interactive/video_interactive.html
pod/main/static/css/pod.css
pod/playlist/static/css/playlist.css
pod/playlist/static/css/videojs-playlist.css
pod/playlist/templates/playlist/playlist_list.html
pod/playlist/templates/playlist/playlist_player.html
pod/recorder/templates/recorder/link_record.html
pod/recorder/templates/recorder/record_delete.html
pod/video/templates/channel/form_theme.html
pod/video/templates/channel/list_theme.html
pod/video/templates/channel/theme_edit.html
pod/video/templates/videos/card.html
pod/video/templates/videos/video-form.html
pod/video/templates/videos/video_delete.html
pod/video/templates/videos/video_edit.html

J'ai revu la playlist, tu me diras ce que tu en penses.
Je ne sais pas si le javascript fonctionnait avant dans la playlist, mais cela ne fonctionnait pas après mes modifs. Je pense avoir corrigé ... mais faut bien tester, je ne suis pas doué en jquery.

Modification des boutons + playlist

---

pod/video/templates/videos/card.html

Titre de vidéo : majuscule uniquement à la première lettre

Video title : only capitalize first letter

---

pod/main/static/css/pod.css
pod/main/templates/navbar.html

Proposition de mettre l'image de l'utilisateur à la place des initiales.
Supprimer la branche si cette fonction n'est pas désirée ;-)

Profile image in header if available

---

pod/main/static/css/pod.css
pod/video/templates/videos/video-info.html
pod/video/templates/videos/video.html

La page de description n'est pas visible s'il n'y a pas d'infos, pas de tags et si ce n'est pas une vidéo 3D. J'ai revu aussi la page info pour mettre l'image de profil en plus gros.

Video summary not visible if empty

---

pod/live/templates/live/live.html
pod/locale/fr/LC_MESSAGES/django.po

Update the management of the end of the streaming live (if possible).
Check if strem (file .m3u8) exists, or not, to be sure that live is really stopped.

Loic bonavent/live video on hold update

---

pod/authentication/templates/authentication/login.html
pod/main/templatetags/custom_tags.py

Fix HIDE_LOCAL_LOGIN

---

pod/locale/fr/LC_MESSAGES/django.po
pod/main/templates/navbar_collapse.html

Remove the translation of button letter, in the users list.

Remove translation button letter for the users list

---

pod/authentication/populatedCASbackend.py

Je n'ai pas pu tester car mon install n'es pas relié à un ldap mais j'ai tout testé avec le shell et logiquement tout fonctionne.
J'ai gardé une compatibilité avec le setting de base pour éviter de le modifier partout. On peut mettre un simple string en url ou un tuple de string qui vont correspondre aux autres hosts.

Allow to have referral ldap hosts

---

.gitignore
pod/custom/settings_local.py.example

@ptitloup  @JoshuaBaubry  premiere propisition qu'est ce que vous en pensez ?

Add example settings file

---

pod/custom/settings_local.py.example
pod/video/views.py

Add VIEW_STATS_AUTH: authentificated to show video stats view

---

pod/video/forms.py
pod/video/static/js/validate-date_delete-field.js
pod/video/templates/videos/video_edit.html
pod/video/views.py

Fix js error date format

---

pod/video/forms.py

@ptitloup @JoshuaBaubry  un fix backend, qui m'a echappé tout à l'heure !

Fix : bug validate video date_delete backend

---

pod/chapter/static/js/videojs-chapters.js
pod/video/templates/videos/video-iframe.html

Le problème des chapitre qui ne sont pas chargés est du à la fonction gettext qui ne veut pas se load. Je ne sais pas du tout pourquoi elle ne se charge pas , j'ai cherché pendant un petit moment mais j'ai fais un fix en attendant (après ces 3 lignes ne sont pas vraiment utile, dans le panneau des chapitres le mot chapitre est bien traduit en fr)

bugfix : chapter not display in iframe mode

---

pod/completion/forms.py
pod/completion/static/css/completion.css
pod/completion/static/js/caption_maker.js
pod/completion/static/js/completion.js
pod/completion/templates/contributor/list_contributor.html

@ptitloup @JoshuaBaubry  quelques petites corrections et un bug

Review code

---

pod/completion/static/js/caption_maker.js
pod/podfile/static/podfile/js/filewidget.js
pod/podfile/templates/podfile/list_folder_files.html

Permettre la selection d'un fichier en cliquant sur l'image, ceci ameliore l'experience utilisateur.

Select caption file

---

pod/video/static/css/comment-style.css

Améliorer la possibilité de s'adapter au css local

Improve comment video system

---

pod/main/static/js/main.js
pod/video/models.py
pod/video/templates/channel/channel.html

@ptitloup @JoshuaBaubry Une demande: organiser les thèmes depuis la sidebar par ordre alphabétique.

Sort themes alphabetically in sidebar

---

pod/custom/settings_local.py.example
pod/video/bbb.py
pod/video/management/commands/bbb.py

- Management of last caracter (os.separator) for DEFAULT_BBB_PATH
- Management of last caracter (/) for BBB_SERVER_URL
- Management of BBB_USERNAME_FORMAT for matching BBB username to Pod user

Loic bonavent/bbb to pod 3

---

pod/locale/fr/LC_MESSAGES/django.po
pod/main/templates/aside.html
pod/main/templates/base.html
pod/main/templates/navbar.html
pod/main/templates/navbar_collapse.html

Hello !
Here is a small commit to improve navigation with screen readers.
(remove 2 contrasts errors, and some accessibility alerts on Pod's home page)
tested with https://wave.webaim.org/

 Improve accessibility of Pod home page 

---

pod/main/static/css/videojs-controlbar.css
pod/main/static/js/videojs-info-controlbar.js
pod/main/static/js/videojs-logo-controlbar.js
pod/video/models.py
pod/video/templates/channel/channel_edit.html
pod/video/templates/videos/video-header.html
pod/video/templates/videos/video-iframe.html

+ Render "Info Icon" white for a better contrast
+ Info icon is now picked from "{% static ...%}" instead of absolute "/static/..."
+ Adds CSS highlighting on videojs controlbar buttons when they're active
+ some code formatting + remove useless trailing spaces

Minor VideoJS CSS improvements

---

pod/video/static/js/video_category.js

@ptitloup  j'avais oublié d'intégrer ces modifications suite à certaines des remarques de @JoshuaBaubry hier .

Fix alert color, replace click to mousedown, remove console.log

---

pod/video/static/js/video_category.js

@ptitloup @JoshuaBaubry petit oubli de cacher le loader apres l'affichage du msg d'erreur sur le champ vide !

Hide loader after displaying error msg

---

pod/video/static/css/video_stats_view.css
pod/video/static/js/video_stats_view.js
pod/video/templates/videos/video_stats_view.html
pod/video/tests/test_stats_view.py
pod/video/views.py

@ptitloup @JoshuaBaubry quelques petites modifications dans le code des statistiques de vue de la vidéo

Improve video stat view

---

pod/custom/settings_local.py.example
pod/video/forms.py

Video manage required fields

---

pod/podfile/static/podfile/css/podfile.css
pod/podfile/static/podfile/js/filewidget.js
pod/podfile/templates/podfile/list_folder_files.html
pod/podfile/templates/podfile/userfolder.html
pod/podfile/views.py

@JoshuaBaubry  @ptitloup je viens de fixer le problème du click sur la vignette dans podfile et j'en ai profité pour mieux indenter le code template et fixer quelques css

Fix podfile click on thumbnail

---

pod/video/static/css/comment-style.css
pod/video/static/js/comment-script.js

@JoshuaBaubry @ptitloup j'ai une extension qui me permet de formatter le code proprement avec un espacement en Tab.
Donc j'en ai profiter pour mieux indenter le code.

Done: Add comment reply button

---

pod/video/management/commands/unarchive_video.py

Update date delete to default date delete
Change user id argument hlep text

Update unarchive video command

---

pod/video_search/views.py

add theme title and overlay title in search field

Improve search

---

pod/video/models.py
pod/video/rest_views.py

Please find enclosed work on pod webservices for moodle repository plugin work that we had started
WIP moodle plugin can be find here https://github.com/cperves/moodle-repository_pod/tree/devel
devel branch
do not hesitate to ask me for more suggestions of work on it
meet you on the esup RC channel
Céline

moodle pod plugin webservices needs

---

pod/video/models.py

this triggering an error for all audio format when calling user_videos with mp3 extension for example

height property of media does not exists when this is an audio

---

pod/main/static/js/main.js
pod/video/static/css/comment-style.css

now alert-info will also fade out after 5s, like alert-succes
+ each alert has right color, not all in green 'succes' like

CSS/JS : alert-info corrections

---

pod/video/static/css/comment-style.css
pod/video/static/js/comment-script.js
pod/video/templates/videos/video.html

@ptitloup @JoshuaBaubry 
- Fixer lors de la construction de l'url dans la vue autre que origin/video/video_slug ex : channel/video/video_slug
- Fixer bug conflict lors de la mise à jour du nombre de vote

Fix loading comment when video in channel

---

pod/bbb/templates/bbb/card.html
pod/bbb/templates/bbb/live_card.html
pod/live/templates/live/building.html
pod/live/templates/live/live.html
pod/live/templates/live/lives.html

Add css classes to some html elements

---

pod/podfile/static/podfile/css/podfile.css
pod/podfile/templates/podfile/home.html
pod/podfile/templates/podfile/home_content.html

Done
C'est bon pour moi.
@ptitloup 
@JoshuaBaubry 
- Enlever l'autocompletion au niveau de l'input, lorsqu'on partage un dossier, qui avait tendance à cacher le resultat de la recherche
- Enlever le CollapseAside et Page Filter, qui n'est pas utile dans la vue /podfile et casse le positionnement des elements (css)
- Fixer le ratio en hauteur entre les dossiers et dossiers partagés de l'utilisateur (voire image)
Avant
Après

Review podfile

---

pod/authentication/populatedCASbackend.py
pod/authentication/tests/test_populated.py
pod/authentication/tests/test_views.py

Check populate user from CAS and LDAP attributes

Add populated test 

---

pod/video/forms.py
pod/video/templates/videos/video_record.html

remove user id in data post in form - fixbug with user_channels in video_form

fix bug with screen recorder and video form

---

.github/workflows/code_formatting.yml
pod/video/views.py

remove unused check

---

pod/locale/fr/LC_MESSAGES/django.po
pod/video/templates/videos/video-info.html

Show MP4 links of a video ine the share tab to easily integrate in H5P activity or bigbluebutton meeting
The translate locale fr is update too

Add MP4 video links for BBB and H5P in share tab

---

pod/video/management/commands/clean_video_files.py

This command delete useless video files (not associated with a video Object)

New command "clean_video_files"

---

pod/video/templates/videos/video-info.html

[BugFix] Correct a small html typo

---

pod/authentication/views.py
pod/recorder/views.py

check if next link start with / to prevent external redirect link

---

pod/authentication/templates/authentication/login.html
pod/authentication/utils.py
pod/authentication/views.py
pod/locale/fr/LC_MESSAGES/django.po
pod/main/forms.py
pod/main/static/css/pod.css
pod/main/views.py
pod/settings.py
pod/video_search/views.py

[BugFix] correct a small bug on video_search, happening when a selected_facet is repeated
(see https://localhost:8080/search/?q=foo&selected_facets=type.slug:bar1&selected_facets=type.slug:bar2 )
+ prevent robots from indexing authentication login template
+ add a verbose style for logging in django console / reduce default django console logging level to "warning" only.
+ [Bugfix] ignore error when contact-us form is submitted with subject not in SUBJECT_CHOICES (already cleaned by super(ContactUsForm).clean())
+ CSS : add ".alert-error" class for styling error messages
+ add some missing pydocstrings

[Done] Bugfix on video_search, happening when a selected_facet is repeated

---

pod/video/rest_views.py

Ajout de l'identifiant du tenant dans l'API REST vidéo
Ajout du filtrage des vidéos en fonction de l'identifiant du tenant

[DONE] Add Tenant identifier in video REST API

---

pod/authentication/backends.py

Mise à jour des informations user et owner lors de l'authentification shibboleth :
auth_type
affiliation
is_staff
nom, prenom, adresse_email
site
Création et ajout automatique dans le groupe correspondant à l'affiliation

[DONE] Update Owner information with shibboleth backend + add group affiliation

---

.github/workflows/pod.yml
pod/custom/settings_local.py.example
pod/main/context_processors.py
pod/main/templates/navbar.html
pod/video/templates/videos/video_edit.html

- New template for video edit
- Force chunked upload

Fix Dev3 [Css & Other]

---

pod/custom/settings_local.py.example
pod/video/transcript.py
requirements.txt

As you probably know by now, Mozilla stopped working on DeepSpeech so we migrated to Coqui-STT instead.
You can also find our new model for french (v0.8) available on [Coqui's Zoo](https://coqui.ai/french/commonvoice-fr/v0.8).

Use  🐸-STT

---

pod/main/rest_router.py
pod/recorder/rest_views.py

add RecordingFileTreatment to rest api

add RecordingFileTreatment to rest api

---

pod/custom/settings_local.py.example
pod/main/settings.py
pod/video/models.py

Ajout d'une propriété sur la vidéo permettant de compter le nombre de vue sur une durée en nombre de jours.

[WIP] Recent viewcount

---

pod/bbb/templates/bbb/list_meeting.html
pod/bbb/templates/bbb/live_card.html
pod/bbb/templates/bbb/live_publish_meeting.html
pod/completion/templates/video_caption_maker.html
pod/completion/templates/video_completion.html
pod/enrichment/templates/enrichment/edit_enrichment.html
pod/enrichment/templates/enrichment/group_enrichment.html
pod/live/templates/live/building.html
pod/live/templates/live/live.html
pod/main/templates/base.html
pod/main/templates/contact_us.html
pod/recorder/templates/recorder/claim_record.html
pod/recorder/templates/recorder/link_record.html
pod/video/templates/channel/channel.html
pod/video/templates/channel/theme_edit.html
pod/video/templates/videos/filter_aside_category.html
pod/video/templates/videos/link_video.html
pod/video/templates/videos/video-all-info.html
pod/video/templates/videos/video-form.html
pod/video/templates/videos/video-info.html
pod/video/templates/videos/video.html

Remove "title" attributes on links when it duplicates link content.
+ minor code formatting

[DONE] Accessibility / Cleaning

---

pod/video/models.py

to prevent an error on makemigrations

[Done] Add default SITE_ID value for Channel and Discipline models

---

pod/live/views.py

manquait des parenthèses pour appel méthode du modèle

fix affichage my_events

---

pod/recorder/templates/recorder/opencast-studio.html
pod/recorder/views.py
pod/video/encode.py

Add missing "[theme]" settings to work with OpenCast-studio latest release (2022-06-15)

[DONE] [Bugfix] compatibility with latest OpenCast-Studio

---

.github/workflows/code_formatting.yml
.github/workflows/pod.yml

Replace "dev" branch by new "develop" in Github Workflows

Apply GitHub workflows on develop

---

pod/video/Encoding_video.py
pod/video/Encoding_video_model.py
pod/video/encode.py

[DONE] fix in encoding

---

pod/live/templates/live/event-all-info.html
pod/main/static/css/pod.css
pod/video/static/js/comment-script.js
pod/video/templates/videos/video-all-info.html
pod/video/templates/videos/video.html

Correct Css on mobile :
* wrap very long links in video descriptions
* pod-aside-collapse button has now a fixed position
JS :
* Replace "myTab" id by "pod-infos-tabs"

[DONE] Minor CSS & JS bugfixes

---

pod/locale/fr/LC_MESSAGES/djangojs.po
pod/main/static/css/iframe.css
pod/main/templates/base.html
pod/main/templates/navbar_collapse.html

Pod Aside menu (+ collapse button), Breadrumbs and Footer are no more rendered just to be hidden with CSS.

[DONE] No more render nav menus on iframe

---

pod/live/templates/live/event_card.html
pod/live/templatetags/event_tags.py
pod/live/views.py

suite à une remarque judicieuse de @LoicBonavent 
_ un utilisateur anonyme doit voir les events qui n'ont pas de groupe d'accès
_ un utilisateur authentifié ne doit pas voir un évènement restreint à un groupe dont il ne fait pas parti

[DONE] correction filtres affichage prochains évènements

---

pod/enrichment/templates/enrichment/video_enrichment.html
pod/video/views.py

check if url doesn't match with add or edit, add version to oembed other apps than video (enrichment for example)

[DONE] fix oembed

---

pod/custom/ConfigurationPod.md

[DONE] Update ConfigurationPod.md 

---

pod/live/admin.py
pod/live/models.py
pod/live/tests/test_models.py

cannot add a new broadcaster after qrcode feature

[Done] Fix liveevent qrcode in admin part

---

pod/live/templatetags/event_tags.py
pod/main/templates/navbar.html

remove 'My events' button in navbar if user can't create one

[DONE] Fix navbar 'My events' button display

---

pod/completion/admin.py
pod/main/configuration.json

Replace MODEL_PARAM by TRANSCRIPTION_MODEL_PARAM

Update variable configuration

---

pod/recorder/templates/recorder/opencast-studio.html
pod/recorder/tests/test_views.py
pod/recorder/views.py

use re to find external script and internal style to add it in index template in opencast studio

[DONE] fix opencast studio last version

---

pod/main/views.py

- add csrf protect
- Change GET request to POST request
- limit to hundred the number of response

[DONE] Fix user search from navbar

---

pod/video/Encoding_video_model.py

move get user folder object to filepicker part

[DONE] Update Encoding_video_model.py

---

pod/video/static/js/filter_aside_video_list_refresh.js
pod/video/templates/videos/video_list.html

Fix for 3.1 : video list refresh with dynamic filter -> wrong inject method

[DONE] 3.1 FIX - Pampletousse/fix fvideo list refresh with filters

---

pod/main/static/css/pod.css
pod/main/static/js/main.js

replace all forEach instruction for theme using in video edit page...

[DONE] fix theme in video edit page

---

pod/live/live_transcript.py
pod/live/rest_views.py
pod/live/templates/live/event-script.html
pod/live/templates/live/event.html

- clear webvtt file when live ended
- improve script to get and show live transcript
- move script in event-script file and call it only when player is ready

[DONE] Improve live transcript

---

pod/main/static/js/utils.js
pod/video/static/js/regroup_videos_by_theme.js
pod/video/templates/channel/channel.html
pod/video/templates/videos/videos.html
pod/video/views.py

change getting video limit to 12. add dictinct to prevent same video. don't show if no theme

[DONE] Fix video theme

---

pod/main/views.py
pod/urls.py

create info_pod view to send information about pod instance

[DONE] Feature info pod

---

pod/settings.py

Use django setting to log rotate file

[DONE] Update settings.py

---

pod/main/static/css/pod-admin.css
pod/main/static/css/pod.css
pod/main/templates/admin/base_site.html
pod/video/admin.py

Petit fix de la partie admin - il faut vérifier que tout fonctionne bien au niveau de select2 sous différentes parties de l'administration avec différentes version de python (3.7 - 3.8 etc.)

[DONE] Ptitloup/fix admin js

---

pod/enrichment/static/js/enrichment.js
pod/enrichment/templates/enrichment/edit_enrichment.html

BUG : Dans la partie edition des enrichissements, le ckeditor n'était pas chargé. Cette PR corrige ce problème.

[DONE] load js file get by ajax call in enrichment

---

pod/chapter/static/js/chapters.js

Les messages d'erreurs se répètent lors que l'on valide de nouveau le formulaire.

[DONE] Fix : Form to add or edit a chapter

---

pod/chapter/static/js/videojs-chapters.js
pod/main/static/css/dark.css

[DONE] BUGFIX - Correct darkmode colors on chapter manager

---

pod/live/pilotingInterface.py
pod/live/templates/live/event-script.html
pod/live/tests/test_utils.py
pod/live/tests/test_views.py
pod/live/utils.py
pod/live/views.py

[DONE] live : refacto sans modif de fonctionnalité

---

pod/cut/utils.py
pod/live/pilotingInterface.py
pod/video/Encoding_video_model.py
pod/video/models.py
pod/video/utils.py
pod/video/views.py

Je recrée une PR pour séparer le code en double et résolve les reviews de PR #867

[DONE] split duplicate code

---

pod/xapi/tasks.py
pod/xapi/views.py

- change celery tasks to be launch alone
- improve actor in statement

[DONE] improve xAPI

---

pod/video/static/js/filter_aside_video_list_refresh.js
pod/video/static/js/video_category.js
pod/video/views.py

Fix my_videos categories : unwanted reload from /video/my to /videos/ + 404 raised by click on category filter after created

[DONE] Fix my_videos categories

---

dockerfile-dev-with-volumes/README.adoc
dockerfile-dev-with-volumes/pod/Dockerfile
pod/main/context_processors.py
pod/main/test_settings.py
pod/settings.py
pod/urls.py
pod/video/context_processors.py
pod/video/feeds.py
pod/video/rest_views.py
pod/video/templatetags/video_tags.py
pod/video/tests/test_get_available_videos.py
pod/video/tests/test_stats_view.py
pod/video/utils.py
pod/video/views.py
pod/xapi/views.py
requirements-conteneur.txt
requirements-dev.txt

[DONE] Ptitloup/improve cache request

---

pod/video/templates/videos/filter_aside.html

[DONE] add check configuration to show filter in filter aside template

---

pod/video/context_processors.py

ajout de _get_available_videos_filter_() qui retourne le filtre utilisé dans _get_available_videos()_ afin de pouvoir ajouter d'autre conditions avant d'effectuer la requête.
Mise en place pour le nombre de vidéo et la durée affichée dans le footer de la page d'accueil.

[DONE] improve footer request

---

pod/main/static/js/videojs-info-controlbar.js

[DONE] fix constructor in videojs-info-controlbar js file (this file will be deleted after)

---

pod/video_encode_transcript/transcript_model.py

[DONE] fix import setting local in transcript model file

---

pod/video/apps.py

Add `bulk_update` for video password migration

[DONE] Improve password migration

---

pod/video/admin.py

Remove owner filter in video admin due to long loading in video admin page

[DONE] Update admin.py

---

pod/main/configuration.json

[DONE] add CACHE_VIDEO_DEFAULT_TIMEOUT in configuration

---

pod/main/configuration.json
pod/main/management/commands/compareconfiguration.py
pod/main/management/commands/configuration.py

[DONE] Ptitloup/work on configuration

---

pod/main/configuration.json
pod/main/context_processors.py
pod/main/templates/base.html
pod/main/templates/navbar.html
pod/urls.py
pod/video_encode_transcript/encode.py

[DONE] add the parameter USE_NOTIFICATIONS

---

pod/settings.py
requirements.txt

[DONE] change pod version to 3.4.1 and downgrade pillow to 9.5.0

---

pod/meeting/models.py

Fix issues of BBB Scalite : https://github.com/bigbluebutton/bigbluebutton/issues/18913

[DONE] force end of BBB meeting if not create or get status 

---

pod/main/static/css/pod.css
pod/main/test_settings.py
pod/video/models.py
pod/video/templates/videos/card.html
pod/video/templates/videos/video-script.html
pod/video/templatetags/video_tags.py
pod/video/tests/test_models.py
pod/video/tests/test_views.py
pod/video/urls.py
pod/video/views.py

[DONE] Ptitloup/feature resume video playback -> 3.5.0

---

pod/completion/static/js/caption_maker.js

[DONE] Ptitloup/fix caption maker

---

pod/video/context_processors.py

[DONE] add site id from settings

---

pod/settings.py

[DONE] Ptitloup/bump version pod

---

Makefile
pod/chapter/static/css/chapters.css
pod/chapter/static/css/videojs-chapters.css
pod/completion/static/css/caption_maker.css
pod/cut/static/css/video_cut.css
pod/enrichment/static/css/enrichment.css
pod/enrichment/static/css/videojs-slides.css
pod/locale/fr/LC_MESSAGES/django.po
pod/locale/fr/LC_MESSAGES/djangojs.po
pod/locale/nl/LC_MESSAGES/django.po
pod/locale/nl/LC_MESSAGES/djangojs.po
pod/main/static/css/dark.css
pod/main/static/css/pod.css
pod/main/tasks.py
pod/podfile/static/podfile/css/podfile.css
pod/progressive_web_app/utils.py
pod/video/static/css/comment-style.css
pod/video/static/css/video-iframe.css
pod/video/static/css/video_category.css
pod/video/templates/videos/card.html

Display a different title on "bi-lock" icon when content is restricted.
+ Add missing lang strings
+ Correct CSS Typo on rgba()

[DONE] Distinct icons on password protected and restricted video content.

---

pod/main/test_settings.py

[DONE] Ptitloup/add use docker

---

pod/video/templates/videos/video_edit.html
pod/video/views.py
pod/video_encode_transcript/transcript.py
pod/video_encode_transcript/transcript_model.py

…file to improve accessibility of subtitle

[DONE] Ptitloup/improve subtitle accessibility

---

pod/video/forms.py
pod/video/templates/videos/video_edit.html

[DONE] Ptitloup/improve video edit

---

pod/video/views.py

Change title to date_added (default sort column for dashboard videos)

[DONE] Pampletousse/fix change default sort dashboard

---

CONFIGURATION_FR.md

The current issue before modification:

[DONE] Fix web-push-codelab.glitch.me link target in conf doc

---

pod/authentication/backends.py
pod/main/configuration.json

[DONE] Récupération du login pour l'authentification par OPENID 

---

pod/video_encode_transcript/transcript.py

[DONE] Transcription : Adjusting subtitle display timing

---

pod/live/templates/live/event-script.html

- Enable sound on live event (live stream + video on hold)
- Wait 1.5sec before playing video on hold after page load

[DONE] Liveevent unmute

---

pod/video/forms.py

This PR remove the auto fill for the video password field.

[DONE] Fix the auto fill video password field

---

.coveragerc
Makefile
pod/video/management/commands/migrate_bbb_recordings.py
pod_uwsgi.ini

* Adapt script to Mysql/MariaDB
* DB_PARAMS is now a dict with sevral DB (key is the bbb-origin-server-name from BBB records)
* Add IGNORED_SERVERS param for a list of origin_server_name to be ignored
* Add USE_CACHE param to load BBB local xml instead of asking again BBB server
* Add new option "use_export_csv" to export a CSV list of recordings

[DONE] Improve bbb export script

---

.env.dev-exemple
pod/chapter/views.py
pod/completion/admin.py
pod/completion/views.py
pod/dressing/utils.py
pod/enrichment/models.py
pod/enrichment/views.py
pod/main/context_processors.py
pod/main/forms_utils.py
pod/main/views.py
pod/meeting/models.py
pod/meeting/webinar.py
pod/recorder/utils.py
pod/recorder/views.py

[DONE] Clean code

---

pod/recorder/templates/recorder/claim_record.html

Update bad link videojs lang file in claim_record page

[DONE] Fanfounet/bugfix claim record videojs

---

README.md

[DONE] update readme - add some badges ans link

---

pod/video/views.py

In the listing page for all videos, they are now sorted by date added by default.

[DONE] Videos are sorted by date added by default

---

pod/video/management/commands/create_archive_package.py

Include ViewCount in archive Packages
+ correct a small bug

[DONE] Include ViewCount in archive Packages

---

pod/quiz/static/quiz/js/video-quiz-submit.js
pod/quiz/views.py

[DONE] Ptitloup/feature quizz add user answer

---

dockerfile-dev-with-volumes/pod-encode/Dockerfile
dockerfile-dev-with-volumes/pod/Dockerfile
pod/video_encode_transcript/Encoding_video.py
pod/video_encode_transcript/encoding_settings.py

This PR replaces calls to FFmpegthumbnailer and Montage (ImageMagick)
when encoding an overview by a single call to FFmpeg. Because
FFmpegthumbnailer and Montage were not used anywhere else in the
code, it also removes them as dependencies.

⬆️ [DONE] Replace and remove FFmpegthumbnailer and Montage

---

pod/video/forms.py

[DONE] Remove the thumbnail fields for the video creation

---

pod/video/templates/videos/video_more_script.html
pod/xapi/static/xapi/script-video.js
pod/xapi/templates/xapi/xapi_video.html

Add get_setting USE_XAPI in video_more_script.html
Change registration var used by webpush
Add escapejs for description in xapi_video.html

[DONE] Fanfounet/bugfix xAPI

---

pod/video/rest_views.py

[DONE] Ptitloup/fix rest theme

---

pod/video_search/management/commands/create_pod_index.py

Add try except when deleting index if not exist

[DONE] Update create_pod_index.py

---

pod/main/configuration.json
pod/video/management/commands/create_archive_package.py

Replace the HOW_MANY_DAYS static variable by ARCHIVE_HOW_MANY_DAYS, which can be modified by the application's settings.

[DONE] Update create_archive_package.py

---

pod/main/static/css/pod.css
pod/playlist/static/playlist/css/playlist.css

[DONE] Improve the playlist card for the user usability

---

pod/main/static/js/main.js
pod/podfile/static/podfile/js/filewidget.js

[DONE] Ptitloup/fixbug podfile

---

pod/completion/static/js/caption_maker.js
pod/podfile/static/podfile/js/filewidget.js

[DONE] Fix bug with podfile and caption maker

---

pod/video/templates/videos/video_page_content.html
pod/video/views.py

[DONE] Ptitloup/fixbug aristote

---

pod/video_encode_transcript/transcript.py
pod/video_encode_transcript/transcript_model.py

[DONE] use whisper to format vtt subtitle

---

publiccode.yml

Fix https://github.com/EsupPortail/Esup-Pod/issues/1195

[DONE] Add publiccode.yml

---

pod/playlist/rest_views.py
pod/video/rest_views.py
pod/video_encode_transcript/rest_views.py

CI is red on `develop` branch.
This makes it difficult to develop and submit new PR.
Here is a tiny PR that should fix it.

[DONE] formatting: Fix list indentation for green flake8 CI

---

pod/main/templates/block/multi_carousel.html
pod/playlist/rest_views.py
pod/video/rest_views.py
pod/video_encode_transcript/rest_views.py

Corrige le format HTML de l'affichage du bloc "multi caroussel" des pages éditorialisées

[DONE] Fix multi carousel

---

pod/import_video/utils.py
pod/video/management/commands/migrate_bbb_recordings.py

Bonjour,
Certaines requêtes n'étaient pas adaptées pour mysql dans le script de migration pour BBB. J'ai donc ajouté une condition en fonction du type de base précisé dans la variable MOODLE_DB_TYPE
J'avais aussi l'erreur `TypeError: tuple indices must be integers, not str` à cause de certaines chaines dans des tuples. J'ai mis le numéro d'index à la place.
J'ai aussi ajouté une correction pour le module d'import de vidéo, en lien avec #1213, car cela empêchait d'importer les vidéos lors de l'utilisation de l'option --use-import-video avec un BBB < 2.3

[DONE] Fix migration script for bbb

---

publiccode.yml

[DONE] Remove Markdown syntax from publiccode.yml

---

pod/settings.py
pod/video/models.py

Correct default thumbnail size to avoid thumbnail quality downgrade

[DONE] Correct default thumbnail size to avoid thumbnail quality downgrade

---

pod/settings.py
pod/video/models.py

Correct default thumbnail size to avoid thumbnail quality downgrade

---

pod/live/templates/live/event-info.html
pod/main/templates/base.html
pod/main/templates/navbar.html
pod/playlist/templates/playlist/playlist-list-modal.html
pod/video/forms.py
pod/video/models.py
pod/video/templates/videos/video-all-info.html
pod/video/templates/videos/video-element.html
pod/video/templates/videos/video-script.html
pod/video/urls.py
pod/video/utils.py
pod/video_encode_transcript/models.py

* Remove useless html comments
* Translate html comments
* Remove duplicated function get_storage_path_video from video.utils
* Replace '/' by os.path.join in video models
* Remove duplicated code in video-script.html

[DONE] Code cleaning for 3.9.0

---

pod/video/management/commands/check_obsolete_videos.py

Ensure the previous draft state of video is being stored before archiving it.

[DONE] Store draft state before archiving video

---

pod/locale/fr/LC_MESSAGES/django.po
pod/locale/fr/LC_MESSAGES/djangojs.po
pod/locale/nl/LC_MESSAGES/djangojs.po
pod/meeting/forms.py
pod/meeting/static/js/my_meetings.js
pod/playlist/forms.py
pod/playlist/views.py

Manage playlists module for v4.
- Fixed a bug in list editing by a superuser
- Manage ALLOWED_HOSTS for url_has_allowed_host_and_scheme function (if not, a redirect is made to / and not to the referer, after adding a video to a playlist)
No changes in the behaviour for protected videos.

[DONE] Manage playlists for v4

---

CONFIGURATION_EN.md
CONFIGURATION_FR.md
pod/dressing/models.py
pod/dressing/tests/test_models.py
pod/locale/fr/LC_MESSAGES/django.po
pod/locale/fr/LC_MESSAGES/djangojs.po
pod/locale/nl/LC_MESSAGES/djangojs.po
pod/main/configuration.json
pod/main/static/css/pod.css
pod/meeting/forms.py
pod/meeting/static/js/my_meetings.js
pod/playlist/forms.py
pod/playlist/views.py
pod/video/utils.py
pod/video_encode_transcript/Encoding_video.py
pod/video_encode_transcript/encoding_settings.py
pod/video_encode_transcript/tests/test_remote_encode_transcode.py

[DONE] Fanfounet / fix dressing when not audiotrack

---

pod/cut/views.py
pod/import_video/views.py
pod/live/live_transcript.py
pod/main/test_settings.py
pod/meeting/models.py
pod/meeting/webinar_utils.py
pod/video/management/commands/migrate_bbb_recordings.py
pod/video_encode_transcript/transcript.py
setup.cfg

* Remove now unnecessary `# noqa: C901` comments
* Try to Reduce complexity of functions remaining > 9
* Increase SQLite timeout to 40.0 seconds

Increase Flake8 Max Complexity to 9

---

pod/video_encode_transcript/Encoding_video.py
pod/video_encode_transcript/tests/test_remote_encode_transcode.py

fix test duration video for dressing

---

pod/duplicate/tests/test_views.py
pod/duplicate/urls.py
pod/duplicate/views.py
pod/main/test_settings.py

Manage duplicate module for v4:

[DONE] Manage duplicate module for v4

---

dockerfile-dev-with-volumes/pod-encode/Dockerfile
pod/ai_enhancement/tests/test_models.py
pod/ai_enhancement/tests/test_utils.py
pod/ai_enhancement/tests/test_views.py
pod/import_video/tests/test_models.py
pod/main/configuration.json
pod/main/static/css/dark.css
pod/main/static/css/pod.css
pod/main/templates/base.html
pod/playlist/tests/test_forms.py
pod/playlist/tests/test_models.py
pod/recorder/templates/recorder/opencast-studio.html
pod/video_encode_transcript/encoding_tasks.py
pod/video_encode_transcript/transcripting_tasks.py

* Move slider styles out of dark.css, so other sliders will work even when DARKMODE_ENABLED = False
* Set theme to "light" or "dark" when it is set on "auto"
* Replace deprecated `DOMSubtreeModified` by MutationObserver
+ Code formatting:
* Markdown: no bare urls
* Pydocs : imperative mood

Opencast studio for v4

---

pod/main/configuration.json
pod/main/context_processors.py
pod/main/settings.py
pod/main/templates/aside.html

[DONE] Social share

---

pod/video_encode_transcript/transcripting_tasks.py

[DONE] add MEDIA_ROOT from settings_local in transcripting tasks

---

pod/authentication/rest_views.py
pod/locale/fr/LC_MESSAGES/django.po
pod/locale/fr/LC_MESSAGES/djangojs.po
pod/locale/nl/LC_MESSAGES/django.po
pod/locale/nl/LC_MESSAGES/djangojs.po
pod/podfile/static/podfile/js/filewidget.js
pod/podfile/templates/podfile/home_content.html
pod/video/management/commands/check_database_problems.py
pod/video/management/commands/create_thumbnail.py
pod/video/static/js/dashboard.js
pod/video/static/js/video_category.js
pod/video/tests/test_category.py
pod/video/utils.py
pod/video/views.py

Improvements & Fix some bugs for v4:
- Modify options to specify one or more videos id for the 'python manage.py create_thumbnail' command
- Debug the 'change owner' method
- New command that allows to achieve a database consistency check: typically when the old version of "change owner" was used.
- Fix issue #1294: Modify API Rest to add acces group id
- Fix issue #1243: manage file_id and file_type that allows to edit a file
- Fix issue #1242: impossible to apply an access restriction to several videos
- Fix issue #1241: manage errors when create or edit a category

Improve & Fix bugs

---

pod/dressing/templates/my_dressings.html
pod/dressing/templatetags/dressing_buttons.py
pod/dressing/utils.py
pod/dressing/views.py
pod/main/static/css/pod.css
pod/package.json
pod/video/templates/videos/video-script.html

Fix some bugs for v4:
- Fix issue #1310: Manage search filter for administration.
- Fix issue #1223: Manage audio playlist to be not muted by default.
- Update videojs-wavesurfer plugin version.
- Fix issue #1308: Manage rights for users.

Fix some bugs

---

pod/live/static/css/event_list.css
pod/live/templates/live/event-iframe.html
pod/live/templates/live/event-info.html
pod/live/templates/live/event.html
pod/live/templates/live/event_card.html
pod/locale/fr/LC_MESSAGES/django.po
pod/locale/nl/LC_MESSAGES/django.po
pod/main/static/css/pod.css
pod/main/templates/footer.html
pod/video/context_processors.py

Fix some bugs for v4 and makes a few minor visual changes:
- Manage identical height for event card footer and video card footer
- Fix a bug with events date, truncate event title to 70 caracters and show short date to standardize the display
- Change the footer text on the home page

Fix some bugs and makes a few minor visual changes

---

.env.dev-exemple
docker-compose-dev-with-volumes.yml
docker-compose-full-dev-with-volumes-test.yml
docker-compose-full-dev-with-volumes.yml
dockerfile-dev-with-volumes/README.adoc
dockerfile-dev-with-volumes/elasticsearch/dockerfile-elasticsearch-dev
dockerfile-dev-with-volumes/pod-back/Dockerfile
dockerfile-dev-with-volumes/pod-back/my-entrypoint-back.sh
dockerfile-dev-with-volumes/pod-encode/Dockerfile
dockerfile-dev-with-volumes/pod-encode/my-entrypoint-encode.sh
dockerfile-dev-with-volumes/pod-transcript/Dockerfile
dockerfile-dev-with-volumes/pod-transcript/my-entrypoint-transcript.sh
dockerfile-dev-with-volumes/pod-xapi/Dockerfile
dockerfile-dev-with-volumes/pod-xapi/my-entrypoint-xapi.sh
dockerfile-dev-with-volumes/pod/Dockerfile
dockerfile-dev-with-volumes/pod/my-entrypoint.sh
requirements-conteneur.txt

Ceci est un rétro-portage de la PR #1328 vers la branche `develop`.
Ça me sera utile pour mettre en place un environnement Docker de test pour #1170 qui vise la version `develop`.

Rétro-portage des améliorations Docker #1328

---

pod/video/static/js/ajax-display-channels.js

Fix for https://github.com/EsupPortail/Esup-Pod/issues/1346

[DONE] Fix window display for additional channels
