EsupPortail/Esup-Pod

- pod/video/encode.py
@ptitloup Une petite correction du code, permettant d'avoir une ou plusieurs managers d'un établissement et que ce(s) puissent recevoir le mail de fin d'encodage d'une vidéo appartenant à leur établissement.
> Fix: Send encoding email to many managers

- pod/main/static/css/pod.css
- pod/main/static/js/main.js
- pod/video/templates/videos/video-info.html
- pod/video/templates/videos/video_edit.html
J'ai mis le lien du partage en mode brouillon dans la zone d'info sous la vidéo, onglet partage. J'ai vérifié le javascript et découvert des bugs dans le javascript (selon les cases cochées, on pouvait avoir 2 points d'interrogations dans les paramètres d'url). Reste le QR code qui ne fonctionne pas de manière optimale. Il n'accepte que le premier paramètre dans l'url.
> Lien de partage pour vidéo en mode brouillon

- pod/video/templates/videos/video.html
J'avais déjà corrigé le titre des vidéos dans la page qui liste les vidéos (suppression des majuscules à chaque mots pour ne garder que la première majuscule), mais le titre sous la vidéo et dans le breadcrumb était encore en majuscule.
> titre avec majuscule au début

- pod/enrichment/templates/enrichment/video_enrichment-iframe.html
- pod/enrichment/templates/enrichment/video_enrichment.html
… to prevent a "JSON.parse: bad control character in string literal" error in video enrichments.
> [bugfix] [js] Replace tabs by spaces in video enrichments

- pod/custom/settings_local.py.example
- pod/settings.py
- requirements.txt
@ptitloup  @JoshuaBaubry Fixer problème csrf  lors de la soumission du formulaire sur le partage inter-serveur  par iframe des vidéos protégées par un mdp.
PS: Pas besoin de ce package avec la version 3.1 de Django
> Csrf samesite chrome support

- pod/recorder/views.py
The email received by recorder manager was containing a "None" link when USE_CAS is set to false in settings.
Modify and rename the `reformat_url_if_use_cas methos` on pod/recorder/view.py_ by `reformat_url_if_use_cas_or_shib` in order to treat the case when SHIB is activate (and NOT CAS) to make redirect link to the request page after authentification is done.
The method is now returning the initial link if  USE_CAS or USE_SHIB are both False.
> Fix recorder None link in email send when not USE_CAS (but USE_SHIB)

- pod/video/static/js/comment-script.js
Petite Modification dans le code: utilisation de l'API window.scrollTo plutôt que Element.scrollIntoView à cause du support sur les navigateurs
Window.scrollTo API Support :  https://caniuse.com/mdn-api_window_scrollto
Element.scrollIntoView API Support : https://caniuse.com/scrollintoview
> using window api scrollTo instead of element api scrollIntoView

- pod/authentication/populatedCASbackend.py
This pull request assumes that there is no case needing username with spaces when CAS authentication is used. So this behavior is not configurable. However if you feel it should be, I can make it configurable.
> Trim username's spaces when user authenticates via CAS.

- .github/workflows/pod.yml
- pod/authentication/rest_views.py
- pod/live/rest_views.py
- pod/recorder/rest_views.py
- pod/video/rest_views.py
Je propose de supprimer python 3.5 des versions à tester lors du ci/cd et de plutot rajouter python 3.8
> Change Python versions in ci/cd

- pod/video/static/js/filter_aside_video_list_refresh.js
- pod/video/templates/videos/filter_aside.html
- pod/video/templates/videos/video_list.html
- pod/video/templates/videos/videos.html
- pod/video/views.py
Improve filter aside from Videos page : refresh filtered videos list without reloading (GET form request -> GET-Type Ajax calls), update 'videos found' count with translation and plural managment and keep infinite scroll behaviour.
> Improve filter aside from Videos page

- pod/completion/admin.py
- pod/custom/settings_local.py.example
- pod/main/static/css/pod.css
- pod/main/templates/admin/base_site.html
- pod/main/views.py
- pod/settings.py
- pod/video/admin.py
* Add CSS in pod.css to reset django defaults
* Use bootstrap-THEME.css instead of default one
* Call pod.css AFTER bootsrap.css on admin pages
* [JS] set max_duration_date_delete only when necessary to avoid js error.
* Call js.cookie.js in admin base.html to avoid a js error "Undefined Cookies".
> [DONE] Correct CSS for Django 3 Admin pages

- pod/video/views.py
Lors de la création d'une vidéo (en mode chunked) le type attribué par défaut est celui dont l'id est 1. Or si on a supprimé le type N°1 (Other) ça ne marche plus. Dans les settings le paramètre DEFAULT_TYPE_ID semble être là pour ça mais n'est pas utilisé. D'où cette mini-PR
> Use config DEFAULT_TYPE_ID parameter

- pod/main/static/js/main.js
Corrige un problème d'indentation des |- dans la présentation des sous-thèmes
> fix indentation on theme

- .github/workflows/code_formatting.yml
- .github/workflows/pod.yml
* Replace deprecated set-output by >> $GITHUB_OUTPUT
(see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ )
* Upgrade actions/checkout to @V3 and actions/setup-python to @v4 (see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ )
> [DONE] Update Github workflows

- pod/main/views.py
- pod/podfile/views.py
Replaces the `remove_accents` function of `pod/main/views` with that of `pod/video/models`.
The old one returned a Byte, while the Django filter expected a Unicode string.
> [DONE] Fix remove_accents Bug

- pod/recorder/templates/recorder/opencast-studio.html
Correct bad contrast on opencast studio recorder when system mode is "dark" and Pod mode is "light"
> [DONE] Correct bad contrast on opencast studio

- pod/podfile/static/podfile/js/filewidget.js
Erreur d'affichage sur le bouton de pagination.
Dans la partie mes fichiers ( url/podfile ) lorsqu'on click sur le burger menu et qu'on va en bas de la liste de mes dossiers.
Le html est échappé donc il est rendu tel quel.
Surement dû au retrait de JQuery
> [DONE] :bug: podfile fix pagination display

- pod/main/configuration.json
- pod/podfile/views.py
When "jpg" is set as an allowed extension, "JPG" will by allowed too.
> [DONE] Caps allowed file extensions

- pod/completion/utils.py
- pod/completion/views.py
je regroupe le code double dans le fichier completion/views.py
> [DONE] edit completion/views

- pod/main/static/css/pod-admin.css
> 
> Version 3.1
> Partie Admin
> Le bouton "supprimer" n'est pas aligné avec le label du bouton : 
> 
> ![supp_white](https://github.com/EsupPortail/Esup-Pod/assets/34771705/f49d3303-e781-45e9-bcff-6ca411db1300)
> 
> pareil avec un thème noir : 
> 
> ![supp_black](https://github.com/EsupPortail/Esup-Pod/assets/34771705/2cc376a7-0277-4f4c-8bb0-9b96b1bc1b07)
> 
> En plus dans le thème noir lorsqu'on clique sur le bouton supprimer et qu'on arrive à la partie de confirmation, tout le descriptif est invisible : 
> ![confirm_black_hidden](https://github.com/EsupPortail/Esup-Pod/assets/34771705/963e4446-daf8-48f1-a26e-1a3ae2913343)
> 
> Le texte  est de la même couleur que le fond : 
> ![confirm_black_empty](https://github.com/EsupPortail/Esup-Pod/assets/34771705/f1222231-af66-4bcb-862f-e4aa1247 …
> [DONE] Fix : admin css

- pod/chapter/templates/video_chapter.html
- pod/completion/templates/video_completion.html
- pod/cut/templates/video_cut.html
- pod/favorite/static/js/video-favorites.js
- pod/main/static/js/main.js
- pod/video/templates/videos/link_video.html
- pod/video/templates/videos/video_edit.html
- Fix bug in chapter page : `Cannot read properties of null (reading 'addEventListener')`
- Remove favorite form in mange section
> [DONE] Fix : favorite js

- pod/main/configuration.json
- pod/video/templatetags/video_tags.py
Pour la résolution de l'issue #796 , ajout d'un paramètre HOMEPAGE_VIEW_VIDEOS_FROM_NON_VISIBLE_CHANNELS : si la valeur est True, les vidéos d'une chaine non visible sont affichées.
> [DONE] ajout paramètre HOMEPAGE_VIEW_VIDEOS_FROM_NON_VISIBLE_CHANNELS

- pod/video/templates/videos/video-info.html
Hello,
This pull request simply adds the `title` attribute on iframe snippets generated to embed videos. This is a recommandation of [WCAG 2.0](https://www.w3.org/TR/WCAG20-TECHS/H64.html), that advises to define this attribute to describe the content of the frame.
Have a nice day.
> [DONE] Add a title attribute to generated iframe snippets

- pod/recorder/models.py
Change Transcript field : from Boolean to Varchar(2); identical to the Transcript field of the video model.
This fixes the bug when using recorders, which blocked video encoding.
Useful SQL queries for the migration related to this patch:
UPDATE recorder_recorder SET transcript = '' WHERE transcript = 0;
UPDATE recorder_recorder SET transcript = main_lang WHERE transcript = 1;
> [DONE] Recorder, field transcript, from boolean to varchar(2)

- pod/main/static/css/pod.css
+ force long video titles to wrap on  a second line
> [DONE] CSS: prevent default thumbnail to be too small on some screens

- pod/video/forms.py
This PR fix a bug in the administration module which, when editing a video, caused the following error: 
'NoneType' object has no attribute 'owner'
I modified the clean_channel function (created in PR #864) to manage None value.
> [DONE] Fix "Add any video in user channel" in Administration module

- pod/authentication/tests/test_populated.py
- pod/chapter/forms.py
- pod/chapter/models.py
- pod/chapter/static/js/chapters.js
- pod/chapter/static/js/videojs-chapters.js
- pod/chapter/templates/chapter/form_chapter.html
- pod/chapter/templates/video_chapter.html
- pod/chapter/views.py
- pod/enrichment/templates/enrichment/form_enrichment.html
- pod/enrichment/templates/enrichment/video_enrichment-script.html
- pod/enrichment/templates/enrichment/video_enrichment.html
- pod/package.json
- pod/podfile/templates/podfile/customfilewidget.html
- pod/podfile/widgets.py
- pod/video/forms.py
- pod/video/static/js/videojs-logo-controlbar.js
- pod/video/templates/channel/channel_edit.html
- pod/video/templates/channel/form_theme.html
- pod/video/templates/videos/video-all-info.html
- pod/video/templates/videos/video-header.html
- pod/video/templates/videos/video-script.html
- pod/video/templates/videos/video.html
Work on RGAA 11.04 :
"Dans chaque formulaire, chaque étiquette de champ et son champ associé sont-ils accolés (hors cas particuliers) ?"
> [DONE] Improve A11y of chapter edition form

- pod/playlist/apps.py
- pod/video/apps.py
- pod/video/models.py
- Changement de la limite du mot de passe dans le modèle `Video` 80 --> 250.
- Simplification d'expressions du code
- Correction du date_time (datetime naïf --> datetime conscient)
- Utilisation de `bulk_update` pour la création des playlists favoris
- Fix du mot de passe qui pouvait être encrypté plusieurs fois
> [DONE] Fix migrations for 3.4.0

- pod/live/tests/test_utils.py
Le nombre d'essais maximum pour vérification qu'un fichier existe, ou ne change pas de taille, a été augmenté (voir PR #959)
Le test unitaire doit être adapté en conséquence
> [DONE] Fix unit test

- pod/progressive_web_app/static/js/notification-toast.js
Je viens de voir une coquille dans #937, l'enregistrement de la préférence globale de notification était toujours à `true`, cette PR règle le problème.
> Correction de l'enregistrement de la préférence de notification

- pod/main/configuration.json
- pod/main/context_processors.py
- pod/video/templates/videos/filter_aside.html
> [DONE] add filter HIDE_CURSUS 

- pod/settings.py
- pod/video/context_processors.py
- pod/video/management/commands/cache_video_data.py
> [DONE] Use cache to store video data

- pod/main/static/css/dark.css
- pod/video/forms.py
- pod/video/management/commands/create_thumbnail.py
- pod/video/static/js/video_stats_view.js
- pod/video_encode_transcript/Encoding_video_model.py
Fixes 3 bugs for 3.4.0 version:
To check, execute a command like this: "python manage.py create_thumbnail id" 
To check, on a statistics page (/stats_view/), try to change the number of lines or page. Without this bugfix, you can see an "data.filter is not a function" error in the browser console and an icon Loading, and no changes.
To check, with a super admin user, upload a video file, wait for encoding to finish (while still on the editing page) and save. Without this bugfix, you can see an "owner  - this field is required" error.
> [DONE] New 3.4.0 fixes

- pod/main/static/js/filter-aside-element-list-refresh.js
- pod/main/templates/navbar.html
- pod/playlist/static/playlist/js/filter-aside-playlist-list-refresh.js
- pod/playlist/templates/playlist/filter_aside.html
- pod/playlist/templates/playlist/playlists.html
- pod/playlist/tests/test_views.py
- pod/playlist/utils.py
- pod/video/utils.py
- Maintenant la casse des titres pour le tri des vidéos / playlists n'est plus prise en compte.
- Changement de l'ordre des boutons dans le menu de gauche
- Amélioration + ajout de tests unitaires des listes de lecture
> [DONE] Improve sort & menu order

- pod/completion/templates/video_caption_maker.html
- pod/enrichment/templates/enrichment/group_enrichment.html
- pod/import_video/templates/import_video/add_or_edit.html
- pod/live/templates/live/directs.html
- pod/live/templates/live/event-iframe.html
- pod/live/templates/live/event_edit.html
- pod/live/templates/live/event_immediate_edit.html
- pod/main/templates/base.html
- pod/meeting/templates/meeting/add_or_edit.html
- pod/playlist/templates/playlist/add_or_edit.html
- pod/podfile/templates/podfile/home.html
- pod/video/templates/channel/channel_edit.html
- pod/video/templates/channel/theme_edit.html
- pod/video/templates/videos/add_video.html
- pod/video/templates/videos/video-iframe.html
- pod/video/templates/videos/video_edit.html
- pod/video_search/templates/search/search.html
> [DONE] Fix jsi18n

- pod/video/templates/videos/add_video.html
> [DONE] Check extesion allowed video filename

- pod/completion/rest_views.py
In the Rest API, add a video and role filter for contributors.
**Use case examples**:
curl -H 'Content-Type: application/json' -H 'Authorization: Token xxxxx' -X GET https://pod.univ.fr/rest/contributors/?video=xxxx
or
curl -H 'Content-Type: application/json' -H 'Authorization: Token xxxxx' -X GET https://pod.univ.fr/rest/contributors/?role=xxx
> [DONE] In the Rest API, add a video and role filter for contributors

- pod/video_encode_transcript/transcript_model.py
> [DONE] Whisper: To cut long videos during the transcription process

- pod_uwsgi.ini
In case of numerous/long cookies and/or long query string, the HTTP header may exceed default 4k. When it occurs, uwsgi rejects those rejects with error "invalid request block size" and nginx returns HTTP 502. Allowing 8k is a safe value that still allows weird long cookies set on .univ-xxx.fr
> [DONE] do not fail on HTTP requests with numerous/long cookies

- pod/live/templates/live/event-script.html
Rollback change from PR #1075 as it can prevent live to be displayed when on hold video is defined
> [DONE] Liveevent unmute

- pod/live/views.py
When not admin saving live_event discard many_to_many fields.
This is because form.save(commit=False) is used.
Fields have to be manually set after Event is saved or methode save_m2m() has to be called.
[see django doc here ](https://docs.djangoproject.com/en/3.2/topics/forms/modelforms/#the-save-method)
Pour tester :
- se connecter avec un compte non admin ayant les droits de créer un évènement.
- en créer un avec des restrictions sur un groupe et ajouter un propriétaire additionnel.
Avant l'évènement était bien enregistré mais sans le(s) groupe(s), ni propriétaire(s).
La PR doit résoudre ce cas
> [DONE] fix live_event save for many_to_many fields

- pod/recorder/plugins/type_studio.py
- pod/recorder/utils.py
La fonction de suppression des fichiers dans le répertoire OPENCAST_FILES_DIR ne fonctionne pas.
Dans ce répertoire on trouve toujours des dossiers avant de trouver des fichiers. (voir copie écran)
Je propose de changer la méthode pour supprimer fichiers + dossiers
Aussi de changer le nom du répertoire par celui qui peut être défini dans les settings
> [DONE] fix clean opencast folder method

- pod/main/models.py
Having a bug using postgresql with pod I came accros the use of the key word AUTO_INCREMENT [here](https://github.com/EsupPortail/Esup-Pod/blob/df9a5d2b8477fb809e98234ed63b3ac3d8c94295/pod/main/models.py#L20) which doesn't exist in postgresql.
> [DONE] Use maxid to get nextautoincrement

- Makefile
- docker-compose-dev-with-volumes.yml
- docker-compose-full-dev-with-volumes-test.yml
- docker-compose-full-dev-with-volumes.yml
- dockerfile-dev-with-volumes/README.adoc
- dockerfile-dev-with-volumes/pa11y-ci/config.json
- dockerfile-dev-with-volumes/pa11y-ci/config_mobile.json
- dockerfile-dev-with-volumes/pod-back/my-entrypoint-back.sh
- dockerfile-dev-with-volumes/pod-encode/my-entrypoint-encode.sh
- dockerfile-dev-with-volumes/pod-transcript/my-entrypoint-transcript.sh
- dockerfile-dev-with-volumes/pod-xapi/my-entrypoint-xapi.sh
- dockerfile-dev-with-volumes/pod/my-entrypoint.sh
- pod/custom/settings_local_docker_full_test.py
- pod/live/tests/test_models.py
- pod/main/fixtures/initial_data.json
For the sake of simplicity I suggest to run the development server on port 9090 instead of 8080 inside docker containers, to align this with the exposed port. Unless this is motivated by technical reasons I ignore?
I found by working on #1058 that this is sometimes confusing to deal with different ports depending on the context. Communications among docker containers had to use the port 8080 (for instance communication between a peertube and a pod instance) whether pod had to be externally reached with the 9090 port (with my browser).
The initial data for `Site` use the 9090 port.
https://github.com/EsupPortail/Esup-Pod/blob/be947445e4bd649d6e199c9a9cbf218d79a7d498/pod/main/fixtures/initial_data.json#L2-L8
For the AP implementation we rely on `Site` to build absolute URLs. That would lead …
> [DONE] run development server on port 8000

- pod/bbb/tests/test_models.py
- pod/live/tests/test_models.py
- pod/live/tests/test_utils.py
- pod/main/tests/test_models.py
- pod/meeting/tests/test_views.py
- pod/recorder/tests/test_views.py
- pod/video/tests/test_models.py
- pod/video/tests/test_views.py
`assertEquals` (avec un *s*) et `assertRegexpMatches` sont dépréciés et supprimés dans python 3.12
https://docs.python.org/3.11/library/unittest.html#deprecated-aliases
> [DONE] Correction de dépréciations d'assertions

- CONFIGURATION_FR.md
- Makefile
- docker-compose-dev-with-volumes.yml
- docker-compose-full-dev-with-volumes-test.yml
- docker-compose-full-dev-with-volumes.yml
- dockerfile-dev-with-volumes/README.adoc
- dockerfile-dev-with-volumes/pod-back/my-entrypoint-back.sh
- dockerfile-dev-with-volumes/pod-encode/my-entrypoint-encode.sh
- dockerfile-dev-with-volumes/pod-transcript/my-entrypoint-transcript.sh
- dockerfile-dev-with-volumes/pod-xapi/my-entrypoint-xapi.sh
- dockerfile-dev-with-volumes/pod/my-entrypoint.sh
- pod/custom/settings_local_docker_full_test.py
- pod/live/tests/test_models.py
- pod/main/configuration.json
- pod/main/fixtures/initial_data.json
- pod/main/settings.py
- pod/main/test_settings.py
- pod/main/tests/test_views.py
- pod/settings.py
- pod/video_search/management/commands/create_pod_index.py
- pod/video_search/models.py
- pod/video_search/readme
- pod/video_search/utils.py
- pod/video_search/views.py
#1125 proposait d'uniformiser les ports utilisés à l'intérieur et hors des conteneurs dockers, cette PR propose la même chose pour le nom de domaine.
La raison pour laquelle je propose ce changement est encore liée à #1058. L'implémentation d'Activitypub délègue certaines tâches à celery, et ces tâches ont besoin parfois de construire des URL absolues. Étant dans un contexte celery, on ne peut accéder à un objet *request* pour en récupérer le domaine, alors on doit se fier aux objets [Site](https://docs.djangoproject.com/en/5.0/ref/contrib/sites/#django.contrib.sites.models.Site) de Django.
Or, pour le moment `Site` est initialisé pour `localhost`:
https://github.com/EsupPortail/Esup-Pod/blob/cb5f0d5a09949e00a8730973265d61a2c07e15d7/pod/main/fixtures/initial_data.json#L2-L9
En …
> [DONE] Utilisation de l'adresse `pod.localhost` pour le développement

- pod/playlist/templates/playlist/playlist_player.html
When autoplay is activate on a playlist, at the end of the first video play, an ajax request is done to get the next video data.
This request call the playlist_player template wich contains a error in the use of the templatetags method “can_see_playlist_video“ : This method need 2 arguments that must be repectivlely type of a video class and type of playlist class. But the second argument send by the playlist_player template is a type of str class...
So this second argument must be replace by a variable of playlist class.
> [DONE] Fix “Error during template rendering“ on playlist when autoplay is active

- pod/video_encode_transcript/transcript_model.py
The shlex library was imported with a typo, which made the import fail.
This commit fixes that import, and removes the fallback one.
> [DONE] Fix shlex import and remove an unnecessary fallback import

- pod/import_video/views.py
- pod/video/models.py
- requirements.txt
Bugfix
Modifications to the video import module:
- Replace pytube by pytubefix library, and generate PO token (see https://pytubefix.readthedocs.io/en/latest/user/po_token.html)
- Manage the lack of URL field in some Peertube videos
Modifications to the video module:
- Handle exception to avoid sending an error email, for get_thumbnail function (typically when the generated thumbnail presents a problem)
> [DONE] Bugfix import video and thumbnail

- pod/video_search/management/commands/index_videos.py
- pod/video_search/models.py
- pod/video_search/search_template_fr.json
- pod/video_search/tests/test_utils.py
- pod/video_search/utils.py
- pod/video_search/views.py
Manage video_search module for v4:
_Fielddata is disabled on [cursus] in [pod]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead_
> [DONE] Manage video_search module for v4

- pod/video_encode_transcript/encoding_studio.py
- pod/video_encode_transcript/encoding_utils.py
Encoding parameters defined in settings_local.py are taken into account, particularly those for the recorder.
For issue #1274 
- Manage FFMPEG_CMD, FFPROBE_CMD, FFMPEG_CRF, FFMPEG_NB_THREADS, FFPROBE_GET_INFO, FFMPEG_STUDIO_COMMAND from local settings.
- Manage VIDEO_RENDITIONS from local settings.
> Manage local settings for encoding

- pod/settings.py
- requirements.txt
Manage django-chunked-upload for v4:
- Replace django-chunked-upload==2.0.0 by git+https://github.com/juliomalegria/django-chunked-upload.git@master in requirements.txt (wait for a new release in pypi)
- Remove Django 4 hack for ugettext in settings.py
> [DONE] Manage django-chunked-upload for v4

- pod/main/static/css/dark.css
- pod/main/static/css/pod.css
- pod/main/templates/base.html
- pod/main/templates/navbar.html
This pull request aims to enhance both **accessibility** and the overall **user experience**.
An accessibility audit highlighted that the breadcrumb component could be better integrated. With this update, the breadcrumb remains visible and accessible even when users scroll down the page. This makes navigation easier and improves the overall ergonomics of the interface.
Additionally, I’ve applied some visual refinements to modernize the UI.
- Moved the **breadcrumb** below the main navigation bar, now positioned with `fixed-top`.
- **Rounded button borders** for a more modern look.
- **Centered navigation bar content** for improved visual balance and clarity.
> Accessibility Improvement: Sticky Breadcrumb Below the Main Navigation

- Makefile
- pod/video/management/commands/delete_flatpages_migrations.py
- pod/video/management/commands/export_data_from_v3_to_v4.py
- pod/video/management/commands/import_data_from_v3_to_v4.py
Scripts to migrate from Pod v3 to Pod v4:
- Add a command to delete migration files and .pyc files of the flatpages app, and used it in the createDB command
- A script to migrate from Pod v3 to Pod v4: export data from Pod v3.8.x to a JSON file for Pod v4.0.x. Must be executed on Pod v3.8.x server.
- A script to migrate from Pod v3 to Pod v4: import data from Pod v3.8.x JSON file to Pod v4.0.x. Must be executed on Pod v4.0.x server.
As Pod v4 is not yet finalised, these scripts may evolve.
> Scripts to migrate from Pod v3 to Pod v4

- pod/authentication/tests/test_populated.py
- requirements.txt
The shibboleth_remoteuser module available on the Pypi repository has not been update since 5 years.
The code (also accessible on git : https://github.com/Brown-University-Library/django-shibboleth-remoteuser) still working but some syntax are now obsolete.
This PR update the repository to https://gitlab.gwdg.de/discuss-data/django-shibboleth-remoteuser which have more recent reviews
> Update shibboleth_remoteuser repository

- pod/main/admin.py
**BlockAdmin**  
Ajout de l'affichage des informations `order` et `visible` dans l'admin
Avant:
> ![adminBlock](https://github.com/user-attachments/assets/b1746dc2-b0c8-463f-9ed4-e0ee864768cd)
Après : 
> ![adminBlock_after](https://github.com/user-attachments/assets/ed126e3c-10cc-4b81-bc5e-3038f66d4380)
> [DONE] BlockAdmin: ajout infos dans la liste
